/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Class.Akun;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 * Class untuk login ke akun bank
 * @author Kelompok 3 (Bank Code)
 */
public class login extends javax.swing.JFrame {
    
    static private Akun nasabah;
    public String nomorRekening;
    private String noRek,pin;
    private Akun akun = new Akun();
    /**
     * Creates new form transfer
     */
    public login() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        daftarSekarang = new javax.swing.JLabel();
        pinTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginBTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        norekTXT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        daftarSekarang.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        daftarSekarang.setForeground(new java.awt.Color(51, 51, 51));
        daftarSekarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        daftarSekarang.setText("Daftar Sekarang!");
        daftarSekarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daftarSekarangMouseClicked(evt);
            }
        });
        jPanel2.add(daftarSekarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, 38));

        pinTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTxtActionPerformed(evt);
            }
        });
        jPanel2.add(pinTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 30));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PIN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, 38));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo_BANK-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 170, 170));

        loginBTN.setBackground(new java.awt.Color(0, 153, 153));
        loginBTN.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        loginBTN.setForeground(new java.awt.Color(255, 255, 255));
        loginBTN.setText("LOGIN");
        loginBTN.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        loginBTN.setBorderPainted(false);
        loginBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBTNMouseClicked(evt);
            }
        });
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        jPanel2.add(loginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 66, -1));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nomor Rekening");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 38));

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Belum memiliki akun?");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, 38));

        norekTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norekTXTActionPerformed(evt);
            }
        });
        jPanel2.add(norekTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 600, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTxtActionPerformed
    
    /**
     * Method untuk mengecek noRek dan pin
     * @param evt 
     */
    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        //getText untuk mendapatkan text yang diinputkan oleh user 
        //pada text field
        noRek = norekTXT.getText();
        pin = pinTxt.getText();
        
        
        login log = new login();
        //akun.isiDataAkun(noRek);
        
        
        try {
            //Kondisi jika kedua kondisi bernilai True
            if(akun.checkNoRek(noRek, pin)){
                nasabah = new Akun(noRek,pin);
                if(pin.equals(akun.getPin())){ 
                  log.setNomorRekening(noRek);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Akun tidak ditemukan");
            }
        } catch (IOException e) {
            
        }
    }//GEN-LAST:event_loginBTNActionPerformed
    
    /**
     * Method untuk menampilkan design dari class Home
     * ketika button "Login" di click
     * @param evt 
     */
    private void loginBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTNMouseClicked
        home hom = new home(noRek);
        hom.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_loginBTNMouseClicked
    
    /**
     * Method untuk menampilkan design dari class daftarSekarang
     * ketika text "Daftar Sekarang" di click
     * @param evt 
     */
    private void daftarSekarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daftarSekarangMouseClicked
        daftarSekarang reg = new daftarSekarang();
        reg.setVisible(true);
        dispose();
    }//GEN-LAST:event_daftarSekarangMouseClicked

    private void norekTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norekTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_norekTXTActionPerformed

    /**
     * Method getter untuk mengembalikan nilai nomorRekening
     * @return this.nomorRekening
     */   
    public String getNomorRekening(){
        return this.nomorRekening;
    }
    
    /**
     * Method Setter untuk mengatur/mengubah nomorRekening
     * @param nomor 
     */
    public void setNomorRekening(String nomor){
        this.nomorRekening = nomor;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel daftarSekarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginBTN;
    private javax.swing.JTextField norekTXT;
    private javax.swing.JTextField pinTxt;
    // End of variables declaration//GEN-END:variables
}
