/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Class.Akun;
import Class.TarikUang;
import javax.swing.JOptionPane;
import GUI.login;

/**
 * Class untuk melakukan proses tarik tunai
 * @author Kelompok 3 (Bank Code)
 */
public class tariktunai extends javax.swing.JFrame {
    
    private static String norek;

    /**
     * Creates new form tariktunai
     */
    public tariktunai(String norek) {
        this.norek = norek;
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kembaliBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tarikBtn = new javax.swing.JButton();
        PilihanTarik = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank Code - Tarik Tunai");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembaliBtn.setBackground(new java.awt.Color(0, 204, 204));
        kembaliBtn.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        kembaliBtn.setForeground(new java.awt.Color(255, 255, 255));
        kembaliBtn.setText("Kembali");
        kembaliBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        kembaliBtn.setBorderPainted(false);
        kembaliBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliBtnMouseClicked(evt);
            }
        });
        kembaliBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliBtnActionPerformed(evt);
            }
        });
        jPanel1.add(kembaliBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 66, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logo_BANK-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah yang ingin diambil :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, 30));

        tarikBtn.setBackground(new java.awt.Color(0, 153, 153));
        tarikBtn.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        tarikBtn.setForeground(new java.awt.Color(255, 255, 255));
        tarikBtn.setText("Tarik");
        tarikBtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        tarikBtn.setBorderPainted(false);
        tarikBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tarikBtnMouseClicked(evt);
            }
        });
        tarikBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikBtnActionPerformed(evt);
            }
        });
        jPanel1.add(tarikBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 66, -1));

        PilihanTarik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Saldo -", "50000", "100000", "150000", "200000", "250000", "300000", "350000", "400000", "450000", "500000" }));
        jPanel1.add(PilihanTarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Background.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliBtnActionPerformed
    
    //Method untuk melakukan penarikan uang
    private void tarikBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikBtnActionPerformed
       int IndexCombo;
       String Pilihan;
       IndexCombo = PilihanTarik.getSelectedIndex();
       Pilihan = (String)PilihanTarik.getSelectedItem();      
       
       //Memanggil method constructor tanpa parameter
       Akun akun = new Akun();
       akun.isiDataAkun(norek);
       //log.nomorRekening;
       
       int pilihan = Integer.parseInt(Pilihan);
       int saldo = Integer.parseInt(akun.getSaldo());
       
       //Memanggil method constructor dengan parameter
       TarikUang tu = new TarikUang(norek); 
       
       //Kondisi jika IndexCombo tidak bernilai 0
       if(IndexCombo != 0){
            //Kondisi jika saldo bernilai lebih besar/sama dengan pilihan
            if(saldo - pilihan >= 0){
                try{
                 akun.setHasil(norek, tu.GetTotalTransaksi(pilihan));
                } catch (Exception e){

                }
                JOptionPane.showMessageDialog(this, "Tarik uang berhasil");
            } else {
                JOptionPane.showMessageDialog(this, "Saldo Anda kurang!");
            }
       }else{
           JOptionPane.showMessageDialog(this, "Pilihan anda salah");
       }
       
       JOptionPane.showMessageDialog(this, "Tarik uang berhasil");
       PilihanTarik.setSelectedIndex(0);
       
       
    }//GEN-LAST:event_tarikBtnActionPerformed
    
    /**
     * Method untuk menampilkan design dari class Home
     * ketika button "Kembali" di click
     * @param evt 
     */
    private void kembaliBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliBtnMouseClicked
        home hom = new home(norek);
        hom.setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliBtnMouseClicked

    private void tarikBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tarikBtnMouseClicked

    }//GEN-LAST:event_tarikBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tariktunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tariktunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tariktunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tariktunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tariktunai(norek).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> PilihanTarik;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kembaliBtn;
    private javax.swing.JButton tarikBtn;
    // End of variables declaration//GEN-END:variables
}
